[package]
name = "noierrdev-nonce-account"
version = "0.1.0"
edition = "2021"

[dependencies]
axum =  { version = "0.7.9", features = ["default","ws"] }
dotenv = "0.15.0"
solana-client = "2.1.7"
solana-sdk = "2.1.7"
tokio = "1.43.0"
